# Generated by Django 5.2.9 on 2025-12-14 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='ntx.chemical')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcentrationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='ntx.concentrationunit')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('M', 'Male'), ('X', 'Mixed')], default='U', max_length=1)),
                ('researcher', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('cell_line', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=64)),
                ('active_electrode_criterion', models.FloatField(default=6.0)),
                ('network_burst_threshold', models.IntegerField(default=20)),
                ('burst_frequency_threshold', models.FloatField(default=0.3)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('excluded_wells', models.JSONField(blank=True, default=list)),
                ('well_count', models.PositiveIntegerField(default=0)),
                ('condition_count', models.PositiveIntegerField(default=0)),
                ('knockout_stats', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('INGESTED', 'Ingested'), ('FAILED', 'Failed')], default='CREATED', max_length=16)),
                ('default_concentration_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='ntx.concentrationunit')),
            ],
            options={
                'ordering': ['-date', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('concentration', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('is_control', models.BooleanField(default=False)),
                ('wells', models.JSONField(blank=True, default=list)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='ntx.chemical')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='ntx.concentrationunit')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='ntx.experiment')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to='axion/')),
                ('kind', models.CharField(choices=[('AXION_BASELINE', 'Axion Baseline'), ('AXION_EXPOSURE', 'Axion Exposure'), ('LAYOUT', 'Plate Layout'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('div', models.PositiveIntegerField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ntx.experiment')),
            ],
            options={
                'ordering': ['experiment_id', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NeuronalMetricsFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('div', models.PositiveIntegerField()),
                ('metrics_json', models.JSONField()),
                ('qc_json', models.JSONField(blank=True, default=dict)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neuronal_metrics_frames', to='ntx.experiment')),
            ],
            options={
                'verbose_name': 'Neuronal metrics frame',
                'verbose_name_plural': 'Neuronal metrics frames',
                'ordering': ['experiment_id', 'div'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('outlier_method', models.CharField(choices=[('BOXPLOT', 'Boxplot'), ('ZSCORE', 'Z-Score')], default='BOXPLOT', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborating_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='ntx.project'),
        ),
        migrations.AddConstraint(
            model_name='chemical',
            constraint=models.CheckConstraint(condition=models.Q(('canonical__isnull', True), models.Q(('canonical', models.F('id')), _negated=True), _connector='OR'), name='chemical_canonical_not_self'),
        ),
        migrations.AddConstraint(
            model_name='concentrationunit',
            constraint=models.CheckConstraint(condition=models.Q(('canonical__isnull', True), models.Q(('canonical', models.F('id')), _negated=True), _connector='OR'), name='concentration_unit_canonical_not_self'),
        ),
        migrations.AddIndex(
            model_name='condition',
            index=models.Index(fields=['experiment', 'is_control'], name='cond_exp_ctrl_idx'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(fields=('experiment', 'name', 'concentration', 'unit'), name='condition_unique_per_experiment', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='neuronalmetricsframe',
            index=models.Index(fields=['experiment', 'div'], name='neur_metrics_exp_div_idx'),
        ),
        migrations.AddConstraint(
            model_name='neuronalmetricsframe',
            constraint=models.UniqueConstraint(fields=('experiment', 'div'), name='neur_metrics_frame_exp_div_unique'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['project', 'date'], name='experiment_project_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='experiment_project_code_unique'),
        ),
    ]
