# Generated by Django 5.2.9 on 2025-12-14 17:22

from django.db import migrations


def seed_default_project(apps, schema_editor):
    Project = apps.get_model("ntx", "Project")
    default_slug = "default-project"
    Project.objects.get_or_create(
        slug=default_slug,
        defaults={
            "name": "Default Project",
            "description": "Seeded project for quick CLI imports.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ntx", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_default_project,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
