# Generated by Django 5.2.9 on 2026-05-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntx', '0005_alter_experiment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentingestgroup',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingest_groups', to='ntx.concentrationunit'),
        ),
    ]
