# Generated by Django 5.2.9 on 2026-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntx', '0006_alter_experimentingestgroup_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentingestgroup',
            name='wells',
            field=models.CharField(blank=True, default='', help_text='Space-separated wells, e.g. A1 A2 A3', max_length=255),
        ),
    ]
