# Generated by Django 5.2.14 on 2026-10-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntx', '0007_alter_experimentingestgroup_wells'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentingest',
            name='error_stage',
            field=models.CharField(blank=True, choices=[('PARSE', 'Parsing'), ('PROMOTE', 'Promotion')], default='', editable=False, max_length=16),
        ),
    ]
